#!/bin/sh

mkdir -p  ~/.local/bin
cp -rP  build/english-num ~/.local/bin
chmod +x ~/.local/bin/*

cat << EOF >> ~/.zshenv 
  # modified to add ~/.local/bin to PATH
  path+=('~/.local/bin')
  export PATH
EOF
